### ISSUE TITLE
Implementing tests and documentation

### ISSUE THREAD

**Issue by clifinger** [canduma/canduma#5]

**Comment by shirshak55** [comment]
@clifinger I think we can write integration test. And We can use mock http request etc.

**Comment by clifinger** [comment]
@shirshak55 yes I think also, I will make the dev branch when I finish my job. but you can start and do a PR :) thank you by the way !

**Comment by clifinger** [comment]
Ok, done, please do your PR on develop :)

**Comment by shirshak55** [comment]
@clifinger sure i will probably start once i reach home.

**Comment by clifinger** [comment]
@shirshak55 do you want me to take care of this ticket?

**Comment by shirshak55** [comment]
@clifinger yea please

**Comment by olexiyb** [comment]
Hi all, I personally tried to use rust unit [testing](https://actix.rs/docs/testing/), but I found that
 rust is still in an infant state. 

I personally found that [jest](https://jestjs.io/) is way better and flexible and faster to work with
With the combination of [supertest](https://github.com/visionmedia/supertest) that uses superagent, tests are easy to write and easy to maintain.

I also use Clion and it still has issues to run system tests of application that accepting parameters, due to mix of parameters you passing to rust and to application.

Here is a screenshot of unit testing I currently have

![image](https://user-images.githubusercontent.com/352780/78009357-96523c00-7349-11ea-9d0a-c81726af892e.png)

I have organized the execution the way that during start jest will compile API and restart it automatically and run it in debug mode with logging enabled, so you can see debug information from rust code as well as debug information from the test itself. 

I basically took the best from two worlds. 
I think that in most of the cases the web front will be anyway written on javascript (React, Angular, Vue) and for me is OK to use javascript for integration testing.

The question is are you interested in me to submit the patch with jest unit testing?

**Comment by shirshak55** [comment]
@olexiyb hey there i agree the problem is code reuse i guess but i still think node js  & jest is perfect for testing such thing as test usually don't end up in hot path .
