### ISSUE TITLE
Console command scaffolding to add routes, handlers, models, managers etc ...

### ISSUE THREAD

**Issue by clifinger** [canduma/canduma#8]

**Comment by clifinger** [comment]
@olexiyb thank you for your PRS, do you want to be part of that project I have to make Canduma as Framework with lot of useful tools, I want a console to generate code like Laravel in PHP, make in Symfony PHP, or RoR generator ... Do you think you can handle it ?

**Comment by olexiyb** [comment]
@clifinger I have 20 years of C++, but only 2 weeks in rust at this moment :-)
I am currently learning rust for my personal needs, not because of work requirements :-)

From my experience, this is a pretty tough task to write generator and potentially rust may not be the best language to write such generators. 

I personally use a different language for different purposes (an example https://github.com/clifinger/canduma/issues/5#issuecomment-606507080)

Anyway, my point is I am currently moving in a different direction. I need to have a very fast and scalable API, but do not have experience in graphql and rust to work on the generator.

BTW you can take a look into
[feathers cli](https://docs.feathersjs.com/guides/basics/generator.html) as an example of javascript generator.

**Comment by shirshak55** [comment]
For cli  and generator isn't rust way better and faster?  But usually I never find myself using cli in laravel or rails as its always faster to  create new file & use macro of text editor.

**Comment by olexiyb** [comment]
> For cli and generator isn't rust way better and faster? But usually I never find myself using cli in laravel or rails as its always faster to create new file & use macro of text editor.

written on rust code will be blazing fast, but writing on rust is not that fast :-) 
I have used generators just to see example of the code and how to add new service. First setup initial version, commit to git, add service and see the diff. But later I gave up to use as generators generate the code for old versions of libraries, etc, etc...

**Comment by olexiyb** [comment]
BTW, this may be interesting [Askama](https://github.com/djc/askama)

> Askama implements a template rendering engine based on Jinja. It generates Rust code from your templates at compile time based on a user-defined struct to hold the template's context.
